### ISSUE TITLE
H2 Database support

### ISSUE THREAD

**Issue by Toilal** [rvs-fluid-it/dw-jar-to-war#3]
When a H2 database is configured in the dropwizard configuration, it crash the J2EE Container (Tomcat) on deploy.

Is it possible to register a database "the dropwizard way" using wizard-in-a-box ? Is there a recommanded configuration path for database connection using wizard-in-a-box ?

**Comment by Toilal** [comment]
Sorry, i'm still not sure about this issue, i'll reopen if needed ...

PS: It seems to work properly with Tomcat8.

**Comment by rvs-fluid-it** [comment]
No problem what I'm doing is 
Configuration file:

``` yml
...
database:
  driverClass: oracle.jdbc.OracleDriver
  user: ${db.user}
  password: ${db.password}
  url: ${db.url}
  validationQuery: "select 1 from dual"
...
```

(The placeholders will be replaced by the Maven build. The properties are defined in the settings.xml.)

Configuration Java class:

``` java
...
import io.dropwizard.db.DataSourceFactory;

public class MyServiceConfiguration extends Configuration {
    @Valid
    @NotNull
    @JsonProperty("database")
    private DataSourceFactory database = new DataSourceFactory();

    public DataSourceFactory getDataSourceFactory() {
        return database;
    }

    ...
}
```
